/**
 * repositories/AuditRepository.js
 * Firestore operations for the `audit_logs` collection.
 * Document ID = auto-generated by Firestore.
 *
 * Audit logs are append-only — never updated or deleted.
 */

import { BaseRepository } from './BaseRepository.js';
import { COLLECTIONS } from '../config/constants.js';
import { firestore } from '../config/firebaseAdmin.js';
import { paginateQuery } from '../utils/firestoreHelpers.js';

class AuditRepository extends BaseRepository {
  constructor() {
    super(COLLECTIONS.AUDIT_LOGS);
  }

  // ─── Reads ───────────────────────────────────────────────────────────────────

  /**
   * Returns audit logs for a specific user, newest first.
   * @param {string} userId
   * @param {{ limit?: number, startAfter?: any }} [options]
   */
  async findByUser(userId, options = {}) {
    const query = this.collection()
      .where('userId', '==', userId)
      .orderBy('timestamp', 'desc');

    const { docs, lastDoc, hasMore } = await paginateQuery(query, options);
    return {
      items: docs.map((d) => ({ id: d.id, ...d.data() })),
      lastDoc,
      hasMore,
    };
  }

  /**
   * Returns audit logs for a specific action type.
   * @param {string} action
   * @param {{ limit?: number, startAfter?: any }} [options]
   */
  async findByAction(action, options = {}) {
    const query = this.collection()
      .where('action', '==', action)
      .orderBy('timestamp', 'desc');

    const { docs, lastDoc, hasMore } = await paginateQuery(query, options);
    return {
      items: docs.map((d) => ({ id: d.id, ...d.data() })),
      lastDoc,
      hasMore,
    };
  }

  /**
   * Returns audit logs for a specific resource (e.g., a report ID).
   * @param {string} resource
   * @param {{ limit?: number, startAfter?: any }} [options]
   */
  async findByResource(resource, options = {}) {
    const query = this.collection()
      .where('resource', '==', resource)
      .orderBy('timestamp', 'desc');

    const { docs, lastDoc, hasMore } = await paginateQuery(query, options);
    return {
      items: docs.map((d) => ({ id: d.id, ...d.data() })),
      lastDoc,
      hasMore,
    };
  }

  /**
   * Returns audit logs within a date range.
   * @param {Date} from
   * @param {Date} to
   * @param {{ limit?: number, startAfter?: any }} [options]
   */
  async findByDateRange(from, to, options = {}) {
    const query = this.collection()
      .where('timestamp', '>=', from)
      .where('timestamp', '<=', to)
      .orderBy('timestamp', 'desc');

    const { docs, lastDoc, hasMore } = await paginateQuery(query, options);
    return {
      items: docs.map((d) => ({ id: d.id, ...d.data() })),
      lastDoc,
      hasMore,
    };
  }

  // ─── Writes ──────────────────────────────────────────────────────────────────

  /**
   * Logs an audit event.
   * This is the PRIMARY write method — audit logs are append-only.
   *
   * @param {object} entry
   * @param {string} entry.userId    - Actor UID
   * @param {string} entry.action    - Action name (e.g., 'REPORT_APPROVED')
   * @param {string} entry.resource  - Resource ID or path
   * @param {string} [entry.ipAddress]
   * @param {object} [entry.metadata] - Any extra context
   * @returns {Promise<{ id: string }>}
   */
  async log({ userId, action, resource, ipAddress = null, metadata = {} }) {
    const ref = this.collection().doc();

    await ref.set({
      userId,
      action,
      resource,
      ipAddress,
      metadata,
      timestamp: new Date(),
    });

    return { id: ref.id };
  }

  /**
   * Returns the total count of audit log entries.
   * @returns {Promise<number>}
   */
  async count() {
    const snap = await firestore.collection(COLLECTIONS.AUDIT_LOGS).count().get();
    return snap.data().count;
  }

  // Audit logs are immutable — override destructive base methods

  /** @override — Disabled for audit logs */
  async update() {
    throw new Error('AuditRepository: update() is not allowed on audit logs');
  }

  /** @override — Disabled for audit logs */
  async delete() {
    throw new Error('AuditRepository: delete() is not allowed on audit logs');
  }
}

export default new AuditRepository();
