export const ANALYTICS_EVENTS = {
  UPI_CHECK: 'UPI_CHECK',
  REPORT_SUBMITTED: 'REPORT_SUBMITTED',
  REPORT_APPROVED: 'REPORT_APPROVED',
  REPORT_REJECTED: 'REPORT_REJECTED',
  REPORT_DUPLICATE: 'REPORT_DUPLICATE',
  REPORT_ABUSE: 'REPORT_ABUSE',
  USER_CREATED: 'USER_CREATED',
  USER_ACTIVE: 'USER_ACTIVE',
  USER_BLOCKED: 'USER_BLOCKED',
  UPI_BLACKLISTED: 'UPI_BLACKLISTED',
  UPI_UNBLACKLISTED: 'UPI_UNBLACKLISTED'
};
