/**
 * constants/fraudTypes.js
 */

export const FRAUD_TYPES = {
  INVESTMENT_SCAM: 'INVESTMENT_SCAM',
  JOB_SCAM: 'JOB_SCAM',
  MARKETPLACE_SCAM: 'MARKETPLACE_SCAM',
  REFUND_SCAM: 'REFUND_SCAM',
  QR_SCAM: 'QR_SCAM',
  LOTTERY_SCAM: 'LOTTERY_SCAM',
  DIGITAL_ARREST: 'DIGITAL_ARREST',
  KYC_SCAM: 'KYC_SCAM',
  PHISHING: 'PHISHING',
  OTHER: 'OTHER',
};
