/**
 * constants/riskSignals.js
 */

export const RISK_SIGNALS = {
  VERIFIED_REPORTS: 'VERIFIED_REPORTS',
  PENDING_REPORTS: 'PENDING_REPORTS',
  RECENCY: 'RECENCY',
  VELOCITY: 'VELOCITY',
  BLACKLIST: 'BLACKLIST',
  REPORTER_REPUTATION: 'REPORTER_REPUTATION',
  SCAM_CATEGORY: 'SCAM_CATEGORY',
};
